trigger:
- main  # or your branch name

pool:
  name: 'Default'  # <-- replace with your agent pool name

steps:
- task: BrowserStackConfig@0
  inputs:
    BrowserStackServiceEndPoint: 'new connection'
- script: |
    npm install # or mvn install or whatever your repo uses
    npm run test # your repo's runner command
  displayName: 'npm install & test'
- task: BrowserStackResults@1
  inputs:
    browserstackProduct: 'automate'
- task: BrowserStackStopLocal@0
