trigger:
- main  # or your branch name

pool:
  name: 'Default'  # <-- replace with your agent pool name

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'  # or your preferred Node version
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'
- task: BrowserStackConfig@0
  inputs:
    BrowserStackServiceEndPoint: 'Test_browserstack'
- task: BrowserStackResults@1
  inputs:
    browserstackProduct: 'automate'
- script: |
    npm test
  displayName: 'Run tests'


- script: |
    npm run build
  displayName: 'Build the project'